export const ADD_USER = 'ADD_USER';
export const REMOVE_LAST_USER = 'REMOVE_LAST_USER';
export const REMOVE_SELECTED_USER = 'REMOVE_SELECTED_USER';
export const INCREMENT_AUTO_ID = 'INCREMENT_AUTO_ID';